detect:
  log type: wel
  op: and
  rules:
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '4697'
  - case sensitive: false
    op: contains
    path: Event/EventData/ServiceFileName
    value: set
  - case sensitive: false
    op: contains
    path: Event/EventData/ServiceFileName
    value: '&&'
  - op: or
    rules:
    - case sensitive: false
      op: contains
      path: Event/EventData/ServiceFileName
      value: environment
    - case sensitive: false
      op: contains
      path: Event/EventData/ServiceFileName
      value: invoke
    - case sensitive: false
      op: contains
      path: Event/EventData/ServiceFileName
      value: ${input)
  target: log
respond:
- action: report
  metadata:
    author: Nikita Nazarov, oscd.community
    description: Detects Obfuscated Powershell via Stdin in Scripts
    falsepositives:
    - Unknown
    level: high
    references:
    - https://github.com/SigmaHQ/sigma/issues/1009
    tags:
    - attack.defense_evasion
    - attack.t1027
    - attack.execution
    - attack.t1059.001
  name: Invoke-Obfuscation Via Stdin - Security

