detect:
  log type: wel
  op: or
  rules:
  - op: and
    rules:
    - case sensitive: false
      op: is
      path: Event/System/EventID
      value: '4898'
    - case sensitive: false
      op: contains
      path: Event/EventData/TemplateContent
      value: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
  - op: and
    rules:
    - case sensitive: false
      op: is
      path: Event/System/EventID
      value: '4899'
    - case sensitive: false
      op: contains
      path: Event/EventData/NewTemplateContent
      value: CT_FLAG_ENROLLEE_SUPPLIES_SUBJECT
  target: log
respond:
- action: report
  metadata:
    author: Orlinum , BlueDefenZer
    description: Detects certificate creation with template allowing risk permission
      subject
    falsepositives:
    - Administrator activity
    - Proxy SSL certificate with subject modification
    - Smart card enrollement
    level: low
    references:
    - https://www.specterops.io/assets/resources/Certified_Pre-Owned.pdf
    tags:
    - attack.privilege-escalation
    - attack.credential-access
  name: ADCS Certificate Template Configuration Vulnerability

