detect:
  log type: wel
  op: or
  rules:
  - op: and
    rules:
    - case sensitive: false
      op: is
      path: Event/System/EventID
      value: '5007'
    - case sensitive: false
      op: contains
      path: Event/EventData/NewValue
      value: \Windows Defender\Windows Defender Exploit Guard\Controlled Folder Access\AllowedApplications\
    - op: or
      rules:
      - case sensitive: false
        op: contains
        path: Event/EventData/NewValue
        value: \Users\Public\
      - case sensitive: false
        op: contains
        path: Event/EventData/NewValue
        value: \AppData\Local\Temp\
      - case sensitive: false
        op: contains
        path: Event/EventData/NewValue
        value: \Desktop\
      - case sensitive: false
        op: contains
        path: Event/EventData/NewValue
        value: \PerfLogs\
      - case sensitive: false
        op: contains
        path: Event/EventData/NewValue
        value: \Windows\Temp\
  - op: and
    rules:
    - case sensitive: false
      op: is
      path: Event/System/EventID
      value: '5007'
    - case sensitive: false
      op: contains
      path: Event/EventData/OldValue
      value: \Windows Defender\Windows Defender Exploit Guard\Controlled Folder Access\ProtectedFolders\
  target: log
respond:
- action: report
  metadata:
    author: Nasreddine Bencherchali (Nextron Systems)
    description: 'Detects when someone is adding or removing applications or folders
      from exploit guard "ProtectedFolders" or "AllowedApplications"

      '
    falsepositives:
    - Unlikely
    level: high
    references:
    - https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/windows-10-controlled-folder-access-event-search/ba-p/2326088
    tags:
    - attack.defense-evasion
    - attack.t1562.001
  name: Windows Defender Exploit Guard Tamper

