detect:
  event: WEL
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - case sensitive: false
      op: is
      path: event/EVENT/System/EventID
      value: '5007'
    - case sensitive: false
      op: contains
      path: event/EVENT/EventData/NewValue
      value: \Microsoft\Windows Defender\Exclusions
respond:
- action: report
  metadata:
    author: Christian Burkard (Nextron Systems)
    description: Detects the Setting of Windows Defender Exclusions
    falsepositives:
    - Administrator actions
    level: medium
    references:
    - https://twitter.com/_nullbind/status/1204923340810543109
    tags:
    - attack.defense_evasion
    - attack.t1562.001
  name: Windows Defender Exclusions Added

