detect:
  event: WEL
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - case sensitive: false
      op: is
      path: event/EVENT/System/EventID
      value: '854'
    - op: or
      rules:
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: .githubusercontent.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: anonfiles.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: cdn.discordapp.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: ddns.net
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: dl.dropboxusercontent.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: ghostbin.co
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: github.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: glitch.me
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: gofile.io
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: hastebin.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: mediafire.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: mega.nz
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: onrender.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: pages.dev
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: paste.ee
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: pastebin.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: pastebin.pl
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: pastetext.net
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: privatlab.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: privatlab.net
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: send.exploit.in
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: sendspace.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: storage.googleapis.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: storjshare.io
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: supabase.co
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: temp.sh
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: transfer.sh
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: trycloudflare.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: ufile.io
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: w3spaces.com
      - case sensitive: false
        op: contains
        path: event/EVENT/EventData/Path
        value: workers.dev
respond:
- action: report
  metadata:
    author: Nasreddine Bencherchali (Nextron Systems)
    description: 'Detects an appx package added to the pipeline of the "to be processed"
      packages which was downloaded from a suspicious domain.

      '
    falsepositives:
    - Unknown
    level: high
    references:
    - Internal Research
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
    - https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
    - https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
    tags:
    - attack.defense-evasion
  name: Suspicious Remote AppX Package Locations

