detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - op: or
      rules:
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \WMIC.exe
      - case sensitive: false
        op: is
        path: event/ORIGINAL_FILE_NAME
        value: wmic.exe
    - op: and
      rules:
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: call
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: terminate
respond:
- action: report
  metadata:
    author: Nasreddine Bencherchali (Nextron Systems)
    description: Detects calls to the "terminate" function via wmic in order to kill
      an application
    falsepositives:
    - Unknown
    level: medium
    references:
    - https://cyble.com/blog/lockfile-ransomware-using-proxyshell-attack-to-deploy-ransomware/
    - https://www.bitdefender.com/files/News/CaseStudies/study/377/Bitdefender-Whitepaper-WMI-creat4871-en-EN-GenericUse.pdf
    tags:
    - attack.execution
    - attack.t1047
  name: Application Terminated Via Wmic.EXE

