detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - op: or
      rules:
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: ConfigSecurityPolicy.exe
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \ConfigSecurityPolicy.exe
      - case sensitive: false
        op: is
        path: event/ORIGINAL_FILE_NAME
        value: ConfigSecurityPolicy.exe
    - op: or
      rules:
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: ftp://
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: http://
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: https://
respond:
- action: report
  metadata:
    author: frack113
    description: 'Detects the execution of "ConfigSecurityPolicy.EXE", a binary part
      of Windows Defender used to manage settings in Windows Defender.

      Users can configure different pilot collections for each of the co-management
      workloads.

      It can be abused by attackers in order to upload or download files.

      '
    falsepositives:
    - Unknown
    level: medium
    references:
    - https://lolbas-project.github.io/lolbas/Binaries/ConfigSecurityPolicy/
    tags:
    - attack.exfiltration
    - attack.t1567
  name: Arbitrary File Download Via ConfigSecurityPolicy.EXE

