steps:
# SETUP SSH KEYS
- name: 'gcr.io/cloud-builders/git'
  id: set-ssh-keys
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
    git config --global user.email "ops@limacharlie.io"
    git config --global user.name "LimaCharlie Ops"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# CLONE NECESSARY REPOS
- name: 'gcr.io/cloud-builders/git'
  id: clone-repo-sigma
  waitFor: ['set-ssh-keys']
  args:
  - clone
  - --recurse-submodules
  - git@github.com:SigmaHQ/sigma.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  id: clone-repo-sigma-legacy
  waitFor: ['set-ssh-keys']
  args:
  - clone
  - --recurse-submodules
  - git@github.com:SigmaHQ/legacy-sigmatools.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  id: clone-repo-sigma-limacharlie
  waitFor: ['set-ssh-keys']
  args:
  - clone
  - --recurse-submodules
  - git@github.com:refractionPOINT/sigma-limacharlie.git
  - -b
  - rules
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# RESET EXISTING RULES
- name: 'gcr.io/cloud-builders/git'
  id: reset-latest
  waitFor: ['clone-repo-sigma', 'clone-repo-sigma-legacy', 'clone-repo-sigma-limacharlie']
  dir: sigma-limacharlie
  entrypoint: 'bash'
  args:
  - -c
  - |
    git rm -r ./latest || true
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  id: reset-experimental
  waitFor: ['clone-repo-sigma', 'clone-repo-sigma-legacy', 'clone-repo-sigma-limacharlie']
  dir: sigma-limacharlie
  entrypoint: 'bash'
  args:
  - -c
  - |
    git rm -r ./experimental || true
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# GENERATE NEW RULES
- name: python:3
  id: generate-latest
  waitFor: ['reset-latest']
  entrypoint: 'bash'
  args:
  - -c
  - |
    pip3 install ruamel.yaml pyyaml requests termcolor setuptools
    python3 ./scripts/generate_all.py ./sigma/ ./legacy-sigmatools/ ./sigma-limacharlie/latest/ windows/builtin windows/process_creation windows/sysmon

# GENERATE NEW EXPERIMENTAL RULES
- name: python:3
  id: generate-experimental
  waitFor: ['reset-experimental']
  entrypoint: 'bash'
  args:
  - -c
  - |
    pip3 install ruamel.yaml pyyaml requests termcolor setuptools
    python3 ./scripts/generate_all.py ./sigma/ ./legacy-sigmatools/ ./sigma-limacharlie/experimental/ windows/builtin windows/process_creation windows/sysmon windows/dns_query macos/file_event macos/process_creation linux/process_creation

# PUSH CHANGES
- name: 'gcr.io/cloud-builders/git'
  id: push-changes
  waitFor: ['generate-latest', 'generate-experimental']
  dir: sigma-limacharlie
  entrypoint: 'bash'
  args:
  - -c
  - |
    ls -lahR
    git add ./
    git commit -m "`git status --porcelain`"
    git push
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/968258204747/secrets/sigma-deploykey/versions/latest
    env: 'SSH_KEY'

timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'