detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: \..\
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: mshtml
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: RunHTMLApplication
respond:
- action: report
  metadata:
    author: Nasreddine Bencherchali (Nextron Systems)
    description: Detects suspicious command line using the "mshtml.dll" RunHTMLApplication
      export to run arbitrary code via different protocol handlers (vbscript, javascript,
      file, htpp...)
    falsepositives:
    - Unlikely
    level: high
    references:
    - https://twitter.com/n1nj4sec/status/1421190238081277959
    tags:
    - attack.defense_evasion
  name: Mshtml DLL RunHTMLApplication Abuse

