detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - op: or
      rules:
      - case sensitive: false
        op: ends with
        path: event/FILE_PATH
        value: \WMIC.exe
      - case sensitive: false
        op: is
        path: event/ORIGINAL_FILE_NAME
        value: wmic.exe
    - op: and
      rules:
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: call
      - case sensitive: false
        op: contains
        path: event/COMMAND_LINE
        value: uninstall
respond:
- action: report
  metadata:
    author: frack113
    description: Detects the removal or uninstallation of an application via "Wmic.EXE".
    falsepositives:
    - Unknown
    level: medium
    references:
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1047/T1047.md#atomic-test-10---application-uninstall-using-wmic
    tags:
    - attack.execution
    - attack.t1047
  name: Application Removed Via Wmic.EXE

