detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is windows
  - case sensitive: false
    op: ends with
    path: event/FILE_PATH
    value: \DeviceCredentialDeployment.exe
respond:
- action: report
  metadata:
    author: Nasreddine Bencherchali (Nextron Systems)
    description: Detects the execution of DeviceCredentialDeployment to hide a process
      from view
    falsepositives:
    - Unlikely
    level: medium
    references:
    - https://github.com/LOLBAS-Project/LOLBAS/pull/147
    tags:
    - attack.defense-evasion
    - attack.t1218
  name: DeviceCredentialDeployment Execution

