detect:
  events:
  - NEW_PROCESS
  - EXISTING_PROCESS
  op: and
  rules:
  - op: is linux
  - op: and
    rules:
    - case sensitive: true
      op: ends with
      path: event/FILE_PATH
      value: /esxcli
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: system
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: syslog
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: config
    - case sensitive: false
      op: contains
      path: event/COMMAND_LINE
      value: ' set'
respond:
- action: report
  metadata:
    author: Cedric Maurugeon
    description: Detects changes to the ESXi syslog configuration via "esxcli"
    falsepositives:
    - Legitimate administrative activities
    level: medium
    references:
    - https://support.solarwinds.com/SuccessCenter/s/article/Configure-ESXi-Syslog-to-LEM?language=en_US
    - https://developer.broadcom.com/xapis/esxcli-command-reference/7.0.0/namespace/esxcli_system.html
    tags:
    - attack.defense-evasion
    - attack.execution
    - attack.t1562.001
    - attack.t1562.003
    - attack.t1059.012
  name: ESXi Syslog Configuration Change Via ESXCLI

