detect:
  log type: wel
  op: and
  rules:
  - case sensitive: false
    op: is
    path: Event/EventData/Provider_Name
    value: Application Error
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '1000'
  - case sensitive: false
    op: contains
    path: Event/EventData/Data
    value: MsMpEng.exe
  - case sensitive: false
    op: contains
    path: Event/EventData/Data
    value: mpengine.dll
  target: log
respond:
- action: report
  metadata:
    author: Florian Roth (Nextron Systems)
    description: This rule detects a suspicious crash of the Microsoft Malware Protection
      Engine
    falsepositives:
    - MsMpEng might crash if the "C:\" partition is full
    level: high
    references:
    - https://bugs.chromium.org/p/project-zero/issues/detail?id=1252&desc=5
    - https://technet.microsoft.com/en-us/library/security/4022344
    tags:
    - attack.defense_evasion
    - attack.t1211
    - attack.t1562.001
  name: Microsoft Malware Protection Engine Crash

