detect:
  event: WEL
  op: and
  rules:
  - op: is windows
  - op: and
    rules:
    - op: or
      rules:
      - case sensitive: false
        op: is
        path: event/EVENT/System/EventID
        value: '400'
      - case sensitive: false
        op: is
        path: event/EVENT/System/EventID
        value: '401'
    - case sensitive: false
      op: contains
      path: event/EVENT/EventData/PackageFullName
      value: 3669e262-ec02-4e9d-bcb4-3d008b4afac9
respond:
- action: report
  metadata:
    author: Nasreddine Bencherchali (Nextron Systems)
    description: Detects potential installation or installation attempts of known
      malicious appx packages
    falsepositives:
    - Rare occasions where a malicious package uses the exact same name and version
      as a legtimate application
    level: medium
    references:
    - https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
    - https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
    - https://forensicitguy.github.io/analyzing-magnitude-magniber-appx/
    tags:
    - attack.defense-evasion
  name: Potential Malicious AppX Package Installation Attempts

