detect:
  event: WEL
  op: and
  rules:
  - op: is windows
  - op: or
    rules:
    - case sensitive: false
      op: is
      path: event/EVENT/System/EventID
      value: '2032'
    - case sensitive: false
      op: is
      path: event/EVENT/System/EventID
      value: '2060'
respond:
- action: report
  metadata:
    author: frack113
    description: Detects activity when Windows Defender Firewall has been reset to
      its default configuration
    level: low
    references:
    - https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd364427(v=ws.10)
    tags:
    - attack.defense-evasion
    - attack.t1562.004
  name: Windows Defender Firewall Has Been Reset To Its Default Configuration

