detect:
  log type: wel
  op: and
  rules:
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '4697'
  - op: or
    rules:
    - op: matches
      path: Event/EventData/ServiceFileName
      re: \$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[
    - op: matches
      path: Event/EventData/ServiceFileName
      re: \$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[
    - op: matches
      path: Event/EventData/ServiceFileName
      re: \$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[
    - op: matches
      path: Event/EventData/ServiceFileName
      re: \$env:ComSpec\[(\s*\d{1,3}\s*,){2}
    - op: matches
      path: Event/EventData/ServiceFileName
      re: \\*mdr\*\W\s*\)\.Name
    - op: matches
      path: Event/EventData/ServiceFileName
      re: \$VerbosePreference\.ToString\(
    - op: matches
      path: Event/EventData/ServiceFileName
      re: \String\]\s*\$VerbosePreference
  target: log
respond:
- action: report
  metadata:
    author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
    description: Detects all variations of obfuscated powershell IEX invocation code
      generated by Invoke-Obfuscation framework from the code block linked in the
      references
    falsepositives:
    - Unknown
    level: high
    references:
    - https://github.com/danielbohannon/Invoke-Obfuscation/blob/f20e7f843edd0a3a7716736e9eddfa423395dd26/Out-ObfuscatedStringCommand.ps1#L873-L888
    tags:
    - attack.defense_evasion
    - attack.t1027
  name: Invoke-Obfuscation Obfuscated IEX Invocation - Security

